# Generated by Django 5.0.4 on 2024-04-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_email', models.EmailField(max_length=254)),
                ('industry', models.CharField(max_length=100)),
                ('company_gst', models.CharField(max_length=15)),
                ('company_pancard', models.CharField(max_length=20)),
                ('company_website', models.URLField()),
                ('address_line1', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('area_building', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('par_company_name', models.CharField(max_length=100)),
                ('par_industry', models.CharField(max_length=100)),
                ('par_company_gst', models.CharField(max_length=15)),
                ('par_company_pancard', models.CharField(max_length=20)),
                ('par_company_phone', models.CharField(max_length=20)),
                ('par_company_email', models.EmailField(max_length=254)),
                ('par_company_website', models.URLField()),
                ('par_address_line1', models.CharField(max_length=100)),
                ('par_street', models.CharField(max_length=100)),
                ('par_area_building', models.CharField(max_length=100)),
                ('par_landmark', models.CharField(max_length=100)),
                ('par_city', models.CharField(max_length=100)),
                ('par_state', models.CharField(max_length=100)),
                ('par_pincode', models.CharField(max_length=10)),
                ('mark_parent', models.BooleanField(default=False)),
            ],
        ),
    ]
