# Generated by Django 5.0.4 on 2024-04-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='par_company_email',
            field=models.CharField(max_length=255),
        ),
    ]
